name: API Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/api-build.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./api
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore AzDevOpsDashboard.sln
    
    - name: Build
      run: dotnet build AzDevOpsDashboard.sln --no-restore --configuration Release
    
    - name: Run Unit Tests
      run: dotnet test AzDevOpsDashboard.sln --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage"
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-test-results
        path: |
          api/**/TestResults/**/*.xml
          api/**/TestResults/**/*.trx
        retention-days: 30
    
    - name: Upload Code Coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-code-coverage
        path: api/**/TestResults/**/coverage.cobertura.xml
        retention-days: 30
    
    - name: Publish API (Optional - for deployment)
      run: dotnet publish AzDevOpsApi/AzDevOpsApi.csproj --configuration Release --output ./publish
    
    - name: Upload API Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: api-artifacts
        path: api/publish/
        retention-days: 7
